.TH Netmonitor 0.5.2 "January 2 2016" Linux "User Manual"
.SH NAME
netmonitor \- Network Bandwidth Monitor
.SH SYNOPSIS
.B netmonitor
.I [options.....]

.SH DESCRIPTION
.B netmonitor 
is a console application that monitors network interfaces. It displays the transfer rate (upload and download) for each device and the data consumed by each device. The main features of netmonitor are low resource usage, a simple yet effective design, and an easy to understand tabular output. It also logs this data so that it can retain these values after a crash or restart. It displays values whose units change dynamically to scale with the value.

.SH OPTIONS
.IP --config 
Starts the configuration program.
.IP --help
Displays the help menu.

.SH AUTHORS
.TP 
Dwayne Hoy <hellcat82 at iprimus dot com dot au>
.TP 
DoogeJ at GitHub <https://github.com/DoogeJ/netmonitor-ng>
