.TH Netmonitor 0.4b "September 20 2005" Linux "User Manual"
.SH NAME
netmonitor \- Network Bandwidth Monitor
.SH SYNOPSIS
.B netmonitor
.I [options.....]

.SH DESCRIPTION
.B netmonitor 
is a console application that monitors network interfaces. It displays the transfer rate (upload and download) for each device and the data consumed by each device. The main features of netmon are low resource usage, a simple yet effective design, and an easy to understand tabular output. It displays values whose units change dynamically to scale with the value. Its compact display fits in a 9x66 size terminal window.

.SH GENERAL OPTIONS
.IP --config 
Starts the configuration program.
.IP --compact
Removes the spacing lines between each devices.
.IP --help
Displays the help menu.

.SH FORCE UNIT OPTIONS
.IP --forceTKB
Forces the total units to Kilobytes
.IP --forceTMB
Forces the total units to Megabytes
.IP --forceTGB
Forces the total units to Gigabytes
.IP --forceRKB
Forces the data rate units to Kilobytes
.IP --forceRMB
Forces the data rate units to Megabytes
.IP --forceRGB
Forces the data rate units to Gigabytes

.SH BUGS
Forcing a data rate that is to low for the data values will cause destortion to the display.

.SH AUTHOR
Dwayne Hoy <hellcat82 at iprimus dot com dot au>
