.TH Netmonitor 0.5.2 "December 30 2015" Linux "User Manual"
.SH NAME
netmonitor \- Network Bandwidth Monitor
.SH SYNOPSIS
.B netmonitor
.I [options.....]

.SH DESCRIPTION
.B netmonitor 
is a console application that monitors network interfaces. It displays the transfer rate (upload and download) for each device and the data consumed by each device. The main features of netmon are low resource usage, a simple yet effective design, and an easy to understand tabular output. It displays values whose units change dynamically to scale with the value. Its compact display fits in a 9x66 size terminal window.

.SH OPTIONS
.IP --config 
Starts the configuration program.
.IP --help
Displays the help menu.

.SH AUTHOR
Dwayne Hoy <hellcat82 at iprimus dot com dot au>
DoogeJ at GitHub
